"""empty message

Revision ID: 983468879e29
Revises: 
Create Date: 2023-10-15 05:18:28.243824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983468879e29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('administrator', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'administrator')
    # ### end Alembic commands ###
